print ("TALWINDER SINGH - PAL-PAL JEENA")
# print ("""Pal-pal jeena muhaal mera tere bina
# Yeh saaray nashay bekaar teri aankhon ke siwa
# Ghar nahi jaata, mein bahar, rehta tera intezaar
# Mere khuwabon main aa naa kar ke solah singhaar""")
print ("""Pal-pal jeena muhaal mera tere bina
Yeh saaray nashay bekaar teri aankhon ke siwa
Ghar nahi jaata, mein bahar, rehta tera intezaar
Mere khuwabon main aa naa kar ke solah singhaar""")