a = int(input("Enter first number: "))
b = int(input("Enter second number: ")) 

print("square of the first number added to square of second number is:", a**2 + b**2)

#print("The Square of the first number is:", a^2) , #Incorrect way to find square

# ----------------------------------------- IGNORE------------------------------------------- ---


a = int(input("Enter first number: "))
b = int(input("Enter second number: ")) 

print("square of first number is :", a**2
      , "\nsquare of second number is :", b**2)

#if we have to find square of a number we use ** operator not ^ operator

# ----------------------------------------- IGNORE------------------------------------------- ---