#ANSWER BY ME

name = input("Enter your name: ")

date = input("Enter today's date: ")

print(f"""Dear {name}, 
      you are selected 
        {date}""")

#ANSWER BY HARRY SIR

letter = """Dear <|NAME|>,
You Are Selected!   
<|DATE|> """


print(letter.replace("<|NAME|>","SHIVANSHU").replace("<|DATE|>","2nd Dec 2025"))


#---------------------------------------------IGNORE---------------------------------------------