name = "Bittu"

nameshort = name[0:3] # Start index is inclusive and end index is exclusive

print(nameshort)

chracter1 = name[0] # First character
chracter2 = name[1] # Second character
chracter3 = name[2] # Third character
chracter4 = name[3] # Fourth character
chracter5 = name[4] # Fifth character

print(chracter1)
print(chracter2)
print(chracter3)
print(chracter4)
print(chracter5)

# ----------------------------------------- IGNORE------------------------------------------- ---