name = "Bittu"

print("name[0:3]") 

print(name[-4:-1])  # Negative slicing from index -4 to -1 (exclusive)
print(name[1:4])  # Agr Kabhi Negative Slicing krne me problem aaye to Positive Slicing me use convert krlo

print(name[ :4]) # is same as name[0:4]
print(name[-5: ]) # is same as name[-5:-1]
print(name[1: ]) # is same as name[1:5]
print(name[ : ]) # is same as name[0:5] or name[-5:-1] 

# ----------------------------------------- IGNORE------------------------------------------- ---