d = {}

name = input("Enter Your Friends Name: ")
lang = input("Enter Your Favorite Language: ")
d.update({name : lang})


name = input("Enter Your Friends Name: ")
lang = input("Enter Your Favorite Language: ")
d.update({name : lang})


name = input("Enter Your Friends Name: ")
lang = input("Enter Your Favorite Language: ")
d.update({name : lang})


name = input("Enter Your Friends Name: ")
lang = input("Enter Your Favorite Language: ")
d.update({name : lang})


print(d)