a = 23 

aaa = 435

shivanshu = 34

jai = 45 

_shivanshuu = 34 

# All The Above Are Valid variable names



# Below Are Invalid Variable Names


#@samir = 56 # Invalid variable name
# 2name = 67 # Invalid variable name
# shivanshu&jai = 78 # Invalid variable name
# shivanshu jai = 89 # Invalid variable name
# shivanshu-jai = 90 # Invalid variable name
# shivanshu.jai = 12 # Invalid variable name
# shivanshu/jai = 23 # Invalid variable name
# shivanshu*jai = 34 # Invalid variable name
# shivanshu%jai = 45 # Invalid variable name