#ARITHMATIC OPERATORS IN PYTHON
a = 10
b = 3
c = a + b
print(c)

# ----------------------------------------- IGNORE------------------------------------------- ---

#Assignment Operators

a = 4-2 #Assin 4-2 in a
b = 6 
# b +=3 #Increment b by 3 and then assign it to b
b -=3 #Decrement b by 2 and then assign it to b
print(a)
print(b)

# ----------------------------------------- IGNORE------------------------------------------- ---

#Comparison Operators in Python

a = 5
b = 3

print(a==b) #Equal to
print(a!=b) #Not equal to
print(a>b) #Greater than
print(a<b) #Less than
print(a>=b) #Greater than or equal to
print(a<=b) #Less than or equal to


# ----------------------------------------- IGNORE------------------------------------------- ---

#Logical Operators in Python

a = True or False #Logical OR
b = True and False #Logical AND
c = not True #Logical NOT
print(a)
print(b)
print(c)


# ----------------------------------------- IGNORE------------------------------------------- ---



#List of Arithmatic Operators

"""+= #Add and assign
-= #Subtract and assign
*= #Multiply and assign
/= #Divide and assign
%= #Modulus and assign
//= #Floor division and assign
**= #Exponent and assign"""

# ----------------------------------------- IGNORE------------------------------------------- ---



#T R U T H     T A B L E S

#Truth Table for AND Operator

print("True and True =", True and True)
print("True and False =", True and False)
print("False and True =", False and True)
print("False and False =", False and False)

#Truth Table for OR Operator

print("True or True =", True or True)
print("True or False =", True or False)
print("False or True =", False or True)
print("False or False =", False or False)

#Truth Table for NOT Operator

print("not True =", not True)
print("not False =", not False)

# ----------------------------------------- IGNORE------------------------------------------- ---

