a = 5 
t = type(a) #class <int>
print(t)

b = 5.22
t = type(b) #class <float>
print(t)

c = "Shivanshu"
t = type(c) #class <str>
print(t)

d = True
t = type(d) #class <bool>
print(t)

e = None
t = type(e) #class <NoneType>
print(t)

# ----------------------------------------- IGNORE------------------------------------------- --- 

a = "31.2"

b = float(a) #Convert string to float
t = type(b)

print(t)

# ----------------------------------------- IGNORE------------------------------------------- --- 

#List Of Data Types in Python

# Numeric Types: int, float, complex
# Sequence Types: list, tuple, range
# Text Type: str
# Set Types: set, frozenset
# Mapping Type: dict
# Boolean Type: bool
# Binary Types: bytes, bytearray, memoryview
# None Type: NoneType

# ----------------------------------------- IGNORE------------------------------------------- ---