a = input("Enter first number: ")
b = input("Enter second number: ")

print("Number A is:", a)
print("Number B is:", b)

#---------------------------------------- IGNORE------------------------------------------- ---

a = input("Enter first number: ")
b = input("Enter second number: ")

print("sum is :", a + b)  # This will concatenate the strings

#---------------------------------------- IGNORE------------------------------------------- ---

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("sum is :", a + b)  # This will add the integers

#---------------------------------------- IGNORE------------------------------------------- ---

#List Of Built-in Functions to Convert Data Types in Python
# int() - Converts a value to an integer
# float() - Converts a value to a float
# str() - Converts a value to a string
# bool() - Converts a value to a boolean
# list() - Converts a value to a list
# tuple() - Converts a value to a tuple
# dict() - Converts a value to a dictionary
# set() - Converts a value to a set
# chr() - Converts an integer to a character
# ord() - Converts a character to its integer Unicode code point
# complex() - Converts a value to a complex number

#---------------------------------------- IGNORE------------------------------------------- ---
